### ISSUE TITLE
En tant qu'utilisateur, je peux créer une colonne de type recherche

### ISSUE THREAD

**Issue by ThomasKleinhans** [AFP-Graphics/afpnews-deck#12]

**Comment by ZitDantes** [comment]
@ThomasKleinhans 

Dans les créations de conception / déclinaison, nous avions mis le filtre de langue pour la recherche : 

<img width="614" alt="Capture d’écran 2020-11-21 à 13 58 14" src="https://user-images.githubusercontent.com/2536927/99877911-c6fd2380-2c01-11eb-9f86-5a83d25ff048.png">

----

Dans l'app
 
<img width="521" alt="Capture d’écran 2020-11-21 à 13 58 26" src="https://user-images.githubusercontent.com/2536927/99877900-b5b41700-2c01-11eb-9c62-28ecd4d24d23.png">

**Comment by CorentinLC** [comment]
@ZitDantes @ThomasKleinhans 
Curseur et élément recherché non visible dans le champ de recherche
![image](https://user-images.githubusercontent.com/73943498/100132144-49494a00-2e85-11eb-8b3a-ea312adaf83d.png)
![image](https://user-images.githubusercontent.com/73943498/100132408-ad6c0e00-2e85-11eb-8186-03b393d0ad26.png)

Sur chrome, version 86.0.4240.111

**Comment by ZitDantes** [comment]
@CorentinLC lié à la feature du mode nuit. 
Normalement, cette feature sera supprimée. 
tu confirmes @ThomasKleinhans ?

**Comment by ThomasKleinhans** [comment]
je confirme @CorentinLC @ZitDantes

**Comment by ZitDantes** [comment]
Ok en prod
