### ISSUE TITLE
En tant qu'utilisateur, je peux visualiser et utiliser une page de login

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#13]
3 champs : 

* user
* mot de passe
* Choix de la langue

En fonction du choix de la langue, les contenus seront affichés dans cette langue précisément.

**Comment by ZitDantes** [comment]
![KyEpqgkjLM](https://user-images.githubusercontent.com/2536927/99944557-5d9d2200-2d73-11eb-8203-8b165faf7daa.gif)

**Comment by ZitDantes** [comment]
@ThomasKleinhans les photos sont dans le ticket Trello : https://trello.com/c/Cs6CBDLa/36-images-%C3%A9cran-login
Choix d'une image en ramdom.

**Comment by ThomasKleinhans** [comment]
Corrigé et en recette

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans

**Comment by ThomasKleinhans** [comment]
Ajout des images aléatoires @ZitDantes

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans 

@CorentinLC 
Attention, il y a une image qui ne fait pas bien apparaître le logo : 

<img width="1502" alt="Capture d’écran 2020-11-25 à 12 02 08" src="https://user-images.githubusercontent.com/2536927/100219389-3af73e80-2f16-11eb-9ae2-7333c45b01bb.png">

**Comment by CorentinLC** [comment]
@ZitDantes Merci de prévenir, je n'avais pas vu ça, j'en propose une 
EDIT : nouvelle photo ici https://trello.com/c/Cs6CBDLa

**Comment by ZitDantes** [comment]
Ok en prod
