### ISSUE TITLE
En tant qu'utilisateur, je peux créer une colonne de type rubrique

### ISSUE THREAD

**Issue by ThomasKleinhans** [AFP-Graphics/afpnews-deck#16]

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans

**Comment by CorentinLC** [comment]
@ZitDantes 
Différence de wording entre le champ de sélection de la rubrique et son champ d'affichage en tête de colonne 
Exemple dans les rubriques FR : 
![image](https://user-images.githubusercontent.com/73943498/99956711-c2ae4300-2d86-11eb-90a4-af3b5cc99536.png)
version de chrome utilisée 86.0.4240.111

**Comment by CorentinLC** [comment]
@ZitDantes 
La liste des rubriques FR et EN pouvant être sélectionnée n'est pas en adéquation avec le mapping transféré (cf mapping : https://trello.com/c/KjDoKnJW)

**Comment by ZitDantes** [comment]
=> voir carte trello : https://trello.com/c/KjDoKnJW/38-mapping-complet-des-rubriques-fran%C3%A7ais-anglais-allemand-espagnol-portugais-arabe-chinois-trad-chinois-simplifi%C3%A9

**Comment by ThomasKleinhans** [comment]
Corrigé @ZitDantes @CorentinLC

**Comment by ZitDantes** [comment]
Vu. Ok pour moi @ThomasKleinhans

**Comment by ZitDantes** [comment]
Ok en prod
