### ISSUE TITLE
En tant qu'utilisateur, je peux visualiser une nouvelle version graphique d'un article

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#19]
Selon la déclinaison graphique

**Comment by ZitDantes** [comment]
Ok pour moi l'intégration graphique. 

Possible d'ajouter une marge en fin d'article pour éviter que le contenu colle le bas de page @ThomasKleinhans ?
Sinon, le reste ok. 
Et une marge pour entre rubriques et tag

**Comment by ThomasKleinhans** [comment]
Corrigé, en cours de déploiement @ZitDantes

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans

**Comment by ZitDantes** [comment]
Ok en prod
