### ISSUE TITLE
Vérifier les traductions FR/EN

### ISSUE THREAD

**Issue by ThomasKleinhans** [AFP-Graphics/afpnews-deck#26]
Le chemin dans l'app : 

<img width="693" alt="Capture d’écran 2020-11-23 à 11 12 44" src="https://user-images.githubusercontent.com/2536927/99950487-e10f4100-2d7c-11eb-9a63-263e7516e4f2.png">

**Comment by ThomasKleinhans** [comment]
Des traductions peuvent ne pas du tout être implémenté ni en Français, ni en Anglais, elles sont en dur dans le code. Dans ce cas là vous pouvez me les lister ici

**Comment by ZitDantes** [comment]
@ThomasKleinhans 

pour les contenus "À propos" en FR et EN : 

```
À propos de ce site

Ce site, édité par l’AFP, présente l’offre AFP Stories, qui propose des articles multimédias prêts-à-publier et actualisés en continu pour tous les supports digitaux, sites, applications, services connectés ou écrans publics.

Les identifiants qui vous ont été communiqués pour vous connecter à ce site sont confidentiels et ne doivent pas être communiqués à des tiers.
```

---

```
About this website

This website, edited by AFP, showcases the product AFP Stories, which offers constantly updated, ready-to-publish multimedia stories adapted to all digital platforms, websites, applications, connected devices or digital signage.

The credentials provided to you to login to this website are confidential and must not be communicated to third parties.
```

**Comment by ThomasKleinhans** [comment]
Tous les textes ont été variabilisés, vous pouvez retrouver ce qu'il faut traduire dans le fichier en.json (j'ai préfixé tout ce qui est à traduire par "EN:")

Le chemin du fichier est dispo dans la description de l'issue.

@CorentinLC @ZitDantes

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans 

@CorentinLC @julesbonnard 
Vous avez la main pour mettre les traductions qu'il faut. Suffit de changer les wording dans les fichiers de config et de réaliser un push en PROD.
