### ISSUE TITLE
Nettoyer le projet existant des fonctionnalités non désirées

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#27]

**Comment by ThomasKleinhans** [comment]
La fonctionnalité va être supprimée normalement

**Comment by ZitDantes** [comment]
@julesbonnard 
Tu peux lister ici ce que tu as enlevé, stp ?

**Comment by julesbonnard** [comment]
Oui, tu peux le retrouver dans la liste de commits. En gros : 

Le mode nuit
Toute l'installation en pwa (service worker et manifest)
Google analytics
Les politiques CSP (c'est une sécurité mais gênante qd on utilise des bibliothéques comme hotjar)

J'ai aussi renommé le projet en afp stories, dans le readme et le Title HTML. Et supprimé afpdeck du cname, ainsi que le fichier de vérification Google console.

Il vous faut peut être supprimer les donnees du site dans votre navigateur pour avoir la nouvelle version, en raison de la disparition du service worker.

Peut être pourra t-on optimiser a l'avenir les performances, en supprimant la sauvegarde en local des articles, et en permettant un lazy load des colonnes au Scroll horizontal, notamment sur mobile.

**Comment by ZitDantes** [comment]
Top merci @julesbonnard 🙏

**Comment by ZitDantes** [comment]
Ok en prod
