### ISSUE TITLE
En tant qu'user, je peux visualiser une favicon

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#32]
Utiliser le même sur celui du site afp.com : 
https://www.afp.com/sites/default/files/favicon-afp-16x16-rond_0.png

**Comment by ThomasKleinhans** [comment]
Bloqué sur cette fonctionnalité. Cela fonctionne en local chez moi mais lorsque c'est poussé en prod cela ne fonctionne plus, je soupçonne le service worker. A voir avec @julesbonnard lorsqu'il aura nettoyer le projet.

**Comment by ZitDantes** [comment]
Ok en prod
