### ISSUE TITLE
Colonne de contenu plus large que le label en haut de colonne

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#33]
Sur Firefox : 

<img width="1506" alt="Capture d’écran 2020-11-21 à 14 08 17" src="https://user-images.githubusercontent.com/2536927/99878079-33c4ed80-2c03-11eb-96b5-5c5ce378c774.png">

---

Sur Chrome : 

<img width="1548" alt="Capture d’écran 2020-11-21 à 14 10 16" src="https://user-images.githubusercontent.com/2536927/99878099-5525d980-2c03-11eb-8cc3-2a6d3e8abc03.png">

**Comment by ThomasKleinhans** [comment]
Je n'ai pas ce problème sur firefox. Je n'ai que la barre de scroll qui est plus épaisse mais c'est normal

**Comment by ZitDantes** [comment]
@ThomasKleinhans 
Ok pour moi. Je close
