### ISSUE TITLE
En tant qu'utilisateur, je peux voir les choix de l'éditeur

### ISSUE THREAD

**Issue by ThomasKleinhans** [AFP-Graphics/afpnews-deck#37]

**Comment by ZitDantes** [comment]
Mis en place dans le code et caché. 

Sur env. de DEV
![2020-11-25 (1)](https://user-images.githubusercontent.com/2536927/100216231-53655a00-2f12-11eb-8eeb-32efffbe660f.png)

**Comment by ZitDantes** [comment]
@ThomasKleinhans tu pourras indiquer ici le fichier où est commenté le code qui permet de cacher le choix de l'éditeur. 
poke @julesbonnard pour info.
