### ISSUE TITLE
En tant qu'utilisateur, je peux visualiser et utiliser un nouveau menu de navigation

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#4]
@ThomasKleinhans 

* Police de caractère : "sources_sans_pro" => https://fonts.google.com/specimen/Source+Sans+Pro
  * Dispo dans la carte https://trello.com/c/iJG15LAO/11-charte-graphique-afp
* Couleurs : 
  * #325AFB
  * #FFFFFF
  * #000000
* Logo en SVG dans la carte : https://trello.com/c/iJG15LAO/11-charte-graphique-afp
* Icones dans la carte : https://trello.com/c/iJG15LAO/11-charte-graphique-afp **sauf pour le login**, utilisation d'une icone material design de Google (https://material.io/resources/icons/?search=login&style=baseline)

**Comment by ZitDantes** [comment]
@ThomasKleinhans 

Je ré-ouvre. 

<img width="1558" alt="Capture d’écran 2020-11-18 à 10 37 58" src="https://user-images.githubusercontent.com/2536927/99512830-3832a180-298a-11eb-990d-3ab4035a01a4.png">

* J'ai mis le padding gauche et droite à 1.75rem. C'est mieux d'avoir les items avec un peu plus d'espace
* Il manque les icones
* Il manque la barre de séparation entre "se connecter" et les langues

**Comment by ThomasKleinhans** [comment]
- [x] Modification du padding et barre de séparation (reste plus qu'à merge)

En attente de la librairie d'icones pour finaliser l'issue

**Comment by ZitDantes** [comment]
@ThomasKleinhans 

Avec la balise Hotjar (#6) à mettre en place, l'entrée "feedback" dans le menu n'est plus nécessaire. 
On peut supprimer.

**Comment by ThomasKleinhans** [comment]
- [x] Feedback retiré

- [x] Merge des dernières modifications

**Comment by ZitDantes** [comment]
Vu pour les icones. 
C'est bon pour moi @ThomasKleinhans

**Comment by ZitDantes** [comment]
Ok en prod
