### ISSUE TITLE
Point de recette AFP 25/11

### ISSUE THREAD

**Issue by CorentinLC** [AFP-Graphics/afpnews-deck#42]
@ZitDantes @ThomasKleinhans 

CR de ce que je vois comme anomalie à date 
Recette faite sur Chrome version  86.0.4240.111 avec mes identifiants AD

- Dark mode toujours en place excepté sur mobile

-Tête de colonne "tous les sujets"/"all stories" à certaines connexion ou lorsqu'on switche la langue
![image](https://user-images.githubusercontent.com/73943498/100269594-15d6f000-2f57-11eb-8382-df767c2e5471.png)

- Absence du favicon

- Pas de fenêtre hotjar (pas de trace de la balise dans le code d'après ce que j'ai vu)
![image](https://user-images.githubusercontent.com/73943498/100269245-892c3200-2f56-11eb-98bf-281a3a2c8fb8.png)

- Rubrique Planète non alimentée
![image](https://user-images.githubusercontent.com/73943498/100269315-a234e300-2f56-11eb-8a05-2b8b9f4af33f.png)

-Problème d'alimentation des colonnes au clic d'un tag sur une page article. 1. La colonne chargée n'a pas le nom de la rubrique sur laquelle l'utilisateur a cliqué, la rubrique est une "All stories". 2. Dans certains cas, la colonne ne charge pas de contenu. 3. si du contenu se charge, il est dans plusieurs langues au lieu de la langue de la rubrique cliquée.

-Version responsive avec des icônes de paramètre de la colonne qui apparaissent sur le texte lorsque les paramètres de la colonne sont déployés
![image](https://user-images.githubusercontent.com/73943498/100269457-d7413580-2f56-11eb-996d-599276e79263.png)

-Wording "version" mal positionné en responsive et chevauchant le texte
![image](https://user-images.githubusercontent.com/73943498/100269478-e58f5180-2f56-11eb-917a-6d9fc0631c7a.png)

**Comment by ThomasKleinhans** [comment]
- Correction du wording "Version"

- Correction des icones qui passent à travers le panneau "A propos"

- Rubrique Planète : l'appel à l'API se fait bien sur le topic "Environnement", ce problème vient pas de chez nous

- Favicon ajouté

- Le mode sombre est toujours présent dans ton cache mais il est bien définitivement supprimé du site

- Chez moi il y a bien un script hotjar de chargé, on en reparle demain matin

**Comment by CorentinLC** [comment]
Merci @ThomasKleinhans pour ton retour :

- Pour le wording OK
- Correction des icones à travers le panneau "A propos" OK
- Je vois en effet que la rubrique Environnement ne ramène rien via API, je vais investiguer ça de mon côté
- Favicon OK
- mode sombre, OK
- On parle d'Hotjar tout à l'heure
