### ISSUE TITLE
Intégrer une balise hotjar

### ISSUE THREAD

**Issue by ZitDantes** [AFP-Graphics/afpnews-deck#6]
Code 

```<!-- Hotjar Tracking Code for https://afp-graphics.github.io/afpnews-deck -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2108306,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>```

**Comment by ZitDantes** [comment]
Demande un nouveau marqueur GA à Corentin.

**Comment by CorentinLC** [comment]
Pour info, merci ne pas mettre la balise hotjar dans le head de la page de login

**Comment by ThomasKleinhans** [comment]
Bloqué sur cette fonctionnalité. Le code est implémenté mais la console indique que le script de hotjar a été bloqué par Google Analytics. A voir avec @julesbonnard lorsqu'il aura nettoyé le projet.

**Comment by julesbonnard** [comment]
Normalement ça devrait fonctionner avec la suppression des CSP, voir pull request remove-useless-functionnalities

**Comment by ZitDantes** [comment]
Ok en PROD
