### ISSUE TITLE
En tant qu'utilisateur, je veux pouvoir afficher toutes les rubriques d'une langue

### ISSUE THREAD

**Issue by ThomasKleinhans** [AFP-Graphics/afpnews-deck#8]
Lorsque je change de langue pour l'ensemble des contenus : 

* les colonnes sont supprimées
* de nouvelles colonnes avec les rubriques pré-définis sont créées

**Comment by ThomasKleinhans** [comment]
Reste à renseigner toutes les rubriques voulues dans le fichier de configuration

**Comment by ZitDantes** [comment]
@ThomasKleinhans 

Lorsque je choisi une langue, cela génère automatiquement 3 colonnes. 
Alors qu'il faudrait changer la langue uniquement sur les colonnes présentes, non ?

![KKZsKnjxrD](https://user-images.githubusercontent.com/2536927/99642998-75f7fe80-2a4c-11eb-8a2b-3201bbe7b744.gif)

**Comment by ThomasKleinhans** [comment]
Non c'est bien le comportement désiré étant donné que les rubriques sont différentes d'une langue à une autre

**Comment by ZitDantes** [comment]
Ok pour moi @ThomasKleinhans

**Comment by CorentinLC** [comment]
@ZitDantes 
Même commentaire ici : https://github.com/AFP-Graphics/afpnews-deck/issues/2
Pour rappel, les rubriques doivent se suivre dans l'ordre indiqué sur le mapping des rubriques https://trello.com/c/KjDoKnJW

**Comment by ZitDantes** [comment]
Ok en prod
